In [ ]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
sns.set(style="darkgrid")
from time import time

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

# Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.metrics import fbeta_score
from sklearn.metrics import accuracy_score
# Import the three supervised learning models from sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA    

# Pretty display for notebooks
%matplotlib inline
from random import shuffle

In [ ]:

import time
# import pulp as p 
# from random import *
from sklearn import preprocessing
# Add column names to data set
from sklearn.model_selection import train_test_split
data= pd.read_csv('data/german.csv' , skipinitialspace=True)
print(data.head())
print(data.shape[0],data.shape[1])

#sensitive columns name '12'='age','8'='gender/personal_status'  '19'- foreign workers 20'=1(good)/2(bad))

# print(sens)
r=data[['20']]
# print(r)
p=data.shape[0]
for i in range(0,p):  
    if data.loc[i,"12"]>25 :
               data.loc[i,"12"] = 1 
    else :
               data.loc[i,"12"] = 2
    if r.loc[i,'20'] == 1 :
               r.loc[i,"20"] = 1 
    else: 
               r.loc[i,"20"] = 0  
            
print(data['20'].value_counts())            

print(data['8'].value_counts())
print(data['12'].value_counts())
print(data['19'].value_counts())

####################################################################################


# Initialize a scaler, then apply it to the features
'''
scaler = MinMaxScaler() # default=(0, 1)
num_col = dat.dtypes[dat.dtypes != 'object'].index
features_log_minmax_transform = pd.DataFrame(data = dat)
features_log_minmax_transform[num_col] = scaler.fit_transform(features_log_minmax_transform[num_col])


display(features_log_minmax_transform.head())
'''

# sens=DATA[['sex','race']]
#Data_c = pd.get_dummies(features_log_minmax_transform, columns=['sex','race','workclass','education','marital-status','occupation','relationship','native-country'], prefix =['s','r','work','edu','ms','occ','rls','nc'])
m=data.shape[1]
data_c1=data.iloc[:,0:m-1]
min_max_scaler = preprocessing.MinMaxScaler()
data_c2 = min_max_scaler.fit_transform(data_c1)
data_c = pd.DataFrame(data_c2,columns=data_c1.columns)
print(data_c)



#X_test,Y_test_pred,Y_test,e = german_rf(data_c , r)
#print(X_test.iloc[:,:])
X_train, X_test, y_train, y_test = train_test_split(data_c , r, test_size = 0.3, random_state=0, shuffle=True)
X_test.reset_index(drop=True, inplace=True)
# Y_test_pred.reset_index()
y_test.reset_index(drop=True, inplace=True)

# print(X_test)
# print(Y_test_pred)
# print(Y_test)
sens=X_test[['8', '12' ]]
# print(sens)

    


     
# for i in range(0,p):  
#     if r.loc[i,'y'] == 1 :
#                r.loc[i,"y"] = 1 
#     else: 
#                r.loc[i,"y"] = 0 
print(sens['8'].value_counts())            
print(sens['12'].value_counts())
#print(sens['19'].value_counts())
sens1=pd.get_dummies(sens, columns=['8','12'], prefix =['8','12'])
sensitive=sens1.T
print(sensitive) 







# 

   0   1  2  3     4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
0  0   6  4  4  1169  4  4  4  0  0   4   0  67   2   1   2   2   1   1   0   1
1  1  48  2  4  5951  0  2  2  1  0   2   0  22   2   1   1   2   1   0   0   2
2  3  12  4  7  2096  0  3  2  0  0   3   0  49   2   1   1   1   2   0   0   1
3  0  42  2  3  7882  0  3  2  0  2   4   1  45   2   2   1   2   2   0   0   1
4  0  24  3  0  4870  0  2  3  0  0   4   3  53   2   2   2   2   2   0   0   2
1000 21


/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


1    700
2    300
Name: 20, dtype: int64
0    690
1    310
Name: 8, dtype: int64
1    810
2    190
Name: 12, dtype: int64
0    963
1     37
Name: 19, dtype: int64
            0         1     2         3  ...        16   17   18   19
0    0.000000  0.029412  1.00  0.444444  ...  0.666667  0.0  1.0  0.0
1    0.333333  0.647059  0.50  0.444444  ...  0.666667  0.0  0.0  0.0
2    1.000000  0.117647  1.00  0.777778  ...  0.333333  1.0  0.0  0.0
3    0.000000  0.558824  0.50  0.333333  ...  0.666667  1.0  0.0  0.0
4    0.000000  0.294118  0.75  0.000000  ...  0.666667  1.0  0.0  0.0
..        ...       ...   ...       ...  ...       ...  ...  ...  ...
995  1.000000  0.117647  0.50  0.333333  ...  0.333333  0.0  0.0  0.0
996  0.000000  0.382353  0.50  0.111111  ...  1.000000  0.0  1.0  0.0
997  1.000000  0.117647  0.50  0.444444  ...  0.666667  0.0  0.0  0.0
998  0.000000  0.602941  0.50  0.444444  ...  0.666667  0.0  1.0  0.0
999  0.333333  0.602941  1.00  0.111111  ...  0.666667  0.0  0.0  0

In [ ]:
from sklearn.model_selection import cross_val_score  
from sklearn.svm import SVC

rf = RandomForestClassifier(n_estimators=99, max_depth=None, min_samples_split=15, random_state=0)

#svm = SVC(kernel='rbf', random_state=0, gamma=.1, C=10.0,probability=True)
rf.fit(X_train, y_train)
print('The accuracy of the Logistic_Regression classifier on training data is {:.2f}'.format(rf.score(X_train, y_train)))
print('The accuracy of the Logistic_Regression classifier on test data is {:.2f}'.format(rf.score(X_test, y_test)))
print('####Train prediction Label###############################################')
y_train_pred=rf.predict(X_train)
#print(y_1)
y_test_pred=rf.predict(X_test)
e=rf.predict_proba(X_test)
print(e)
print(y_test_pred)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


The accuracy of the Logistic_Regression classifier on training data is 0.90
The accuracy of the Logistic_Regression classifier on test data is 0.76
####Train prediction Label###############################################
[[0.58473416 0.41526584]
 [0.10940278 0.89059722]
 [0.07387113 0.92612887]
 [0.24397644 0.75602356]
 [0.32147506 0.67852494]
 [0.20857757 0.79142243]
 [0.37187644 0.62812356]
 [0.14807527 0.85192473]
 [0.17940454 0.82059546]
 [0.58553193 0.41446807]
 [0.65658032 0.34341968]
 [0.62614566 0.37385434]
 [0.27316001 0.72683999]
 [0.32222267 0.67777733]
 [0.44761898 0.55238102]
 [0.34042877 0.65957123]
 [0.30972699 0.69027301]
 [0.30517761 0.69482239]
 [0.58861635 0.41138365]
 [0.26959707 0.73040293]
 [0.51453073 0.48546927]
 [0.55583589 0.44416411]
 [0.39764598 0.60235402]
 [0.20974686 0.79025314]
 [0.20219262 0.79780738]
 [0.6980013  0.3019987 ]
 [0.16624621 0.83375379]
 [0.29064584 0.70935416]
 [0.07469689 0.92530311]
 [0.58123858 0.41876142]
 [0.19837915 0.80162085]
 [0

In [ ]:
sens=X_test[[ '8','12']]
sens_train_race= X_train[['12']]
sens_train = X_train[['8', '12']]
sens_train_sex = X_train[['8']]

sens_test_race = X_test[['12']]
sens_test_sex = X_test[['8']]

print(sens)
sens1=pd.get_dummies(sens, columns=['8','12'], prefix =['8','12'])
sensitive=sens1.T
print(sensitive) 

       8   12
0    0.0  0.0
1    0.0  0.0
2    0.0  0.0
3    0.0  0.0
4    0.0  0.0
..   ...  ...
295  1.0  1.0
296  0.0  1.0
297  0.0  0.0
298  1.0  0.0
299  1.0  1.0

[300 rows x 2 columns]
        0    1    2    3    4    5    6    ...  293  294  295  296  297  298  299
8_0.0     1    1    1    1    1    1    0  ...    1    0    0    1    1    0    0
8_1.0     0    0    0    0    0    0    1  ...    0    1    1    0    0    1    1
12_0.0    1    1    1    1    1    1    1  ...    1    1    0    0    1    1    0
12_1.0    0    0    0    0    0    0    0  ...    0    0    1    1    0    0    1

[4 rows x 300 columns]


In [ ]:
#----------------------------------FPR, TPR computation--------------------------------------------
print(y_test.iloc[10])
from random import *

def find_eo_stats_multiple(y,y_pred):
    m = 4
    sens_stats = np.zeros((4,m), dtype = int)
    sens_acc = np.zeros(m, dtype = float)
    sizes = np.zeros(m, dtype = int)
    #first row positives, second row negatives, third row true positive, fourth row false positive
    
    
    for i in range(m):
        for j in range(len(y)):
            if(sensitive.iloc[i,j] == 1):
                sizes[i] = sizes[i]+1
                if(y_pred[j]==1):
                    sens_acc[i] = sens_acc[i] + 1
                if(y.iloc[j,0]==1):
                    sens_stats[0][i] =sens_stats[0][i] + 1
                if(y.iloc[j,0]==1 and y_pred[j]==1):
                    sens_stats[2][i] =sens_stats[2][i] + 1
                if(y.iloc[j,0]==0):
                    sens_stats[1][i] =sens_stats[1][i] + 1
                if(y.iloc[j,0]==0 and y_pred[j]==1):
                    sens_stats[3][i] =sens_stats[3][i] + 1    
        sens_acc[i] = sens_acc[i]/sizes[i]
        #print(sens_acc[i],sizes[i])
        
    
    TPR = np.zeros(m,dtype=float)
    FPR = np.zeros(m,dtype=float)
    
    accu = 0
    n = len(y)
    for i in range(n):
        if(y.iloc[i,0] == y_pred[i]):
            accu = accu+1
    
    accu = accu/n
    
    max_tpr = -1 
    min_tpr = 2
    max_fpr = -1
    min_fpr = 2
    
    for i in range(m):
        TPR[i] = sens_stats[2][i]/sens_stats[0][i]
        FPR[i] = sens_stats[3][i]/sens_stats[1][i]
        if(TPR[i] >= max_tpr):
            max_tpr = TPR[i]
        if(TPR[i] <= min_tpr):
            min_tpr = TPR[i]
        if(FPR[i] >= max_fpr):
            max_fpr = FPR[i]
        if(FPR[i] <= min_fpr):
            min_fpr = FPR[i]
    
    for i in  range(m):
        print("TPR of the ",i,"th sensitive groups is",TPR[i])
        
    print("=====================")    
    for i in  range(m):
        print("FPR of the ",i,"th sensitive groups is",FPR[i])
    
    print("=====================")
    for i in  range(m):    
        print("Acceptance Rate of the ",i,"th sensitive groups is",sens_acc[i])
    
    DEO = abs(max_tpr-min_tpr) + abs(max_fpr-min_fpr)
    
    print("The Difference of Equalized odds of the classifier is=",DEO)
    print("Accuracy of the classifier",accu)
    
#find_eo_stats_multiple(y_test,y_pred_CEO)
#find_eo_stats_multiple(y_test,y_test_pred)



        

20    0
Name: 10, dtype: int64


In [ ]:
sens=X_test[[5, 6 ,7, 8, 9,10,11]]
print(sens)
sensitive_final = np.zeros((len(sens.columns),len(y_test)), dtype=int)
for i in range(len(y_test)):
    for j in range(len(sens.columns)):
        if(sens.iloc[i,j]>0):
            sens.iloc[i,j] = 1
        else:
            sens.iloc[i,j] = 0
        sensitive_final[j][i] = sens.iloc[i,j]    
print(sens)            
sensitive = sens.T
print(sensitive_final)

              5         6         7         8         9         10        11
s_male                                                                      
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
...          ...       ...       ...       ...       ...       ...       ...
1      -0.691448  0.691448 -0.096514 -0.171863  3.119166 -0.086521 -2.493490
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863  3.119166 -0.086521 -2.493490
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044
1      -0.691448  0.691448 -0.096514 -0.171863 -0.320598 -0.086521  0.401044


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


         5    6    7    8    9    10   11
s_male                                   
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
...     ...  ...  ...  ...  ...  ...  ...
1       0.0  1.0  0.0  0.0  1.0  0.0  0.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  1.0  0.0  0.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  1.0

[11306 rows x 7 columns]
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 1 1]]


In [ ]:
pip install pulp

     |████████████████████████████████| 14.2 MB 5.0 MB/s 


In [ ]:
import pulp as pl
solver_list = pl.listSolvers(onlyAvailable=True)
print(solver_list)

['PULP_CBC_CMD', 'PULP_CHOCO_CMD']


In [ ]:
accu_all,DP_all,acceptance_rate,alpha_weight = main2(sensitive, y_test, y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
196
149
0.7602040816326531
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
104
65
0.625
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
241
183
0.7593360995850622
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
59
31
0.5254237288135594
data acceptance rates
[0.7602040816326531, 0.625, 0.7593360995850622, 0.5254237288135594]
data DP
0.2347803528190937
sensitive attribute  1
prec reca accuracy for each sens
0.8260869565217391 0.8926174496644296 0.7755102040816326
RanomForest----------total , accepted, aceeptance rate:
196
161
0.8214285714285714
sensitive attribute  2
prec reca accuracy for each sens
0.7317073170731707 0.9230769230769231 0.7403846153846154
RanomForest----------total , accepted, aceeptance rate:
104
82
0.7884615384615384
sensitive attribute  3
prec reca accuracy for each sens
0.8291457286432161 0.9016393442622951 0.784232365145

In [ ]:
pip install pulp

     |████████████████████████████████| 14.2 MB 4.6 MB/s 


In [ ]:
# bilal - am_ind asian black other white female male(actual precision sequence)
# 6         5          4          2                1              0                  3

# ours -s_male, s_female  r_white, r_black, r_asian-pac-islander','r_amer-indian-eskimo','r_other
           
# beta=[6         5          4          2                1              0                  3]

# beta=[beta[6], beta[5],beta[4],beta[2],beta[1],beta[0],beta[3]]


#bilal -female male  am_ind asian  black other white (actual acceptance rate sequence)
#          0      1     2       3     4      5    6   
# ours -s_male, s_female  r_white, r_black, r_asian-pac-islander','r_amer-indian-eskimo', 'r_other
           
# beta=[1       0        6          4            3                   2                    5]


#NG
import time
#import gurobipy as gp
#from gurobipy import GRB
import pulp as p 
def lp_equalized_odds(data1,eps,y_test_pred,e,beta_avg,alpha):
    import pulp as p 
    import math
    
    
    m=data1.shape[0]
    n=data1.shape[1]
    print('dimension of data')
    print(m,n)
    
    
    ############### #  SORTED for ACCURACY ONLY ####
    m=2
    h1=[]
    key1=[]
    cost=np.zeros(n,dtype=int)
    data2=np.zeros((m,n),dtype=int)
    
    for i in range(n):
            h1.append(e[i][1])
            key1.append(i)

        
#print(hc)
#     print(key1)
    
    for i in range(1,len(h1)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h1[j-1]<h1[j]:
                index=j
                var=h1[j]
                h1[j]=h1[j-1]
                h1[j-1]=var

                var2=key1[j]
                key1[j]=key1[j-1]
                key1[j-1]=var2
            else:
                break
    

    
    
    for j in range(len(key1)):    
         data2[0][key1[j]]=j+1
    
    for j in range(n):
        summ=0
        summ=summ+data2[0][j] 
        cost[j]=summ

    Lp_prob = p.LpProblem('Problem', p.LpMinimize)  
    solver = p.getSolver('PULP_CBC_CMD', timeLimit=20)
   
    
#     X=np.zeros(n+1,dtype=p.LpVariable)
    X=np.zeros(n+m+1,dtype=p.LpVariable)
    Y=np.zeros(m,dtype=p.LpVariable)
    
    sizes=np.zeros(m,dtype=int)
#     report_index(index,data1,e):  
    max_size=0
    for i in range(m):
        count=0
        for j in range(n):
            if data1[i][j]==1:
                count=count+1 
        if count>max_size:
            max_size=count
        sizes[i]=count
    print(sizes)    
    #############################33
    
    
    
    
    ###############################
    beta_actual = [0.7621359223300971, 0.6382978723404256]



    
    
    select_sizes=np.zeros(m,dtype=int)
   
    size_final=np.zeros(m,dtype=int)

    for i in range(m):
        var1 = str(n+100+i)
        Y[i]=p.LpVariable(var1,lowBound=0,upBound=1,cat='Continuous')
    
    for i in range(n):
        var1=str(i)       
        X[i]=p.LpVariable(var1,lowBound=0,upBound=1,cat='Integer')
   
    X[n]=p.LpVariable(str(n),lowBound=0,upBound=1,cat='Continuous')  

    tpr = p.LpVariable(str(n+200),lowBound=0,upBound=1,cat='Continuous')  
    fpr = p.LpVariable(str(n+201),lowBound=0,upBound=1,cat='Continuous')  

#     for i in range(m):
#         k=n+i+1
#         var1=str(k)     
#         alpha=(((sizes[i])*(sizes[i]+1))/2)
#         X[i]=p.LpVariable(var1,lowBound=(((beta*sizes[i])*(beta*sizes[i]+1))/2),upBound=alpha,cat='Continuous')
    
        
#     X[n]=  p.LpVariable("z1",lowBound=0)
    #X[n+1]=  p.LpVariable("z2",lowBound=0)
  

    #########objective function#####################
    
#     Lp_prob += 2*X[n+1]+10*X[n+2]+9*X[n+3]+3*X[n+4]
    #alpha=0.8
    #beta_avg = 0.10
    Lp_prob+= p.lpSum([(X[j])*cost[j] for j in range(n)]) 
    #Lp_prob+=1  
    
    #Lp_prob += Y[0]*sizes[0] + Y[1]*sizes[1] >= p.lpSum([Y[j]*sizes[j] for j in np.arange(2,6)])
    #Lp_prob += Y[0]*sizes[0] + Y[1]*sizes[1] <= p.lpSum([Y[j]*sizes[j] for j in np.arange(2,6)])
    
    ##############constraint#################
    #first select the  the number of make female in test data
    #then apply the equalized odd constraints assuming 
    #look at all males which have been predicted positve/and all the females predicted negative
    F_test = 0
    M_test = 0
        
    #for i in range(len(y_test)):
    #    if(data1[0][i]==1 and y_test.iloc[i]==1):
    #        M_test= M_test+1
    #    elif(data1[1][i]==1 and y_test.iloc[i]==1):
    #        F_test= F_test+1
    test_count = np.zeros(m, dtype = int)

    for i in range(len(y_test)):
      for j in range(m): 
        if(data1[j][i]==1 and y_test_pred[i]==1):
            test_count[j] = test_count[j] +1
                
    
    #Lp_prob += (p.lpSum([(X[j])*(data1[0][j])*y_test_pred[j] for j in range(n) if y_test_pred[j]==1])/M_test) <= (p.lpSum([(X[j])*(data1[1][j])*y_test_pred[j] for j in range(n) if y_test_pred[j]==1])/F_test) + 0.0009
    #Lp_prob += (p.lpSum([(X[j])*(data1[0][j])*(1-y_test_pred[j]) for j in range(n) if y_test_pred[j]==0])/(sizes[0]-M_test)) <= (p.lpSum([(X[j])*(data1[1][j])*(1-y_test_pred[j]) for j in range(n) if y_test_pred[j]==0])/(sizes[1]-F_test))+ 0.0009
    for i in range(m):   #TPR constraints
      Lp_prob += (1/test_count[i])*p.lpSum([(X[j])*(data1[i][j])*y_test_pred[j] for j in range(n) if (y_test_pred[j]==1) ]) >= tpr 
      Lp_prob += (1/test_count[i])*p.lpSum([(X[j])*(data1[i][j])*y_test_pred[j] for j in range(n) if (y_test_pred[j]==1 )]) <= tpr + 0.1
    for i in range(m):    #FPR constraints
      Lp_prob += (1/(sizes[i]-test_count[i]))*p.lpSum([(X[j])*(data1[i][j])*(1-y_test_pred[j]) for j in range(n) if (y_test_pred[j]==0)]) >= fpr
      Lp_prob += (1/(sizes[i]-test_count[i]))*p.lpSum([(X[j])*(data1[i][j])*(1-y_test_pred[j]) for j in range(n) if (y_test_pred[j]==0)]) <= fpr + 0.1

    
    for i in range(m):
      #  if i<m:
            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) >= Y[i]*sizes[i]
            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) <= (Y[i]+0.1)*sizes[i]
    
    for i in range(m):
        if beta_actual[i] >= beta_avg:
            Lp_prob += Y[i] >= (1-alpha)*beta_actual[i] + alpha*beta_avg
            Lp_prob += Y[i] <= beta_actual[i]
        else:
            Lp_prob += Y[i] >= (1-alpha)*beta_actual[i] + alpha*beta_avg
            Lp_prob += Y[i] <= beta_avg 
    
           
    #Lp_prob+= p.lpSum([(X[j])*cost[j] for j in range(n)])>=100
        
    #####################################
    #solver = p.CPLEX_PY()
    #solver.buildSolverModel(Lp_prob)
    #Lp_prob.solverModel.parameters.timelimit.set(60)
    #solver.callSolver(P)
    #status = solver.findSolutionValues(Lp_prob)
    #################################################################
    status = Lp_prob.solve(solver)   # Solver 
    print(p.LpStatus[status]) 
    print("objective is:")        
    print(p.value(Lp_prob.objective))
    print("discripency is:") 
    print(p.value(X[n]))
    x=np.zeros(n,dtype=float)

   # The solution status 
    Synth1={}
    Synth2={}
    # # Printing the final solution 
    for i in range(n):
        if(p.value(X[i])==1):
            Synth1[i]=1 
            Synth2[i]=-1
#             if(data1[2][i]==1):
#                 print("no")
        else:
            Synth1[i]=-1
            Synth2[i]=1
    Synthu1=Synth1  
    Synthu2=Synth2  
    
              
    return Synthu1,Synthu2   


In [ ]:
pip install pulp

     |████████████████████████████████| 41.2 MB 75 kB/s 


In [ ]:
pip install pulp

     |████████████████████████████████| 41.2 MB 76 kB/s 


In [ ]:
pip install pulp

In [ ]:
#without accuracy ---> 2
def main2(datax, y_test, y_test_pred,e): 
        
    n=datax.shape[1]
    s=datax.shape[0]    
    data = np.zeros((s, n), dtype = int)
    
    r = np.zeros(n, dtype = int) 
    
    for i in range(n):
        if int(y_test.iloc[i])==1 :
            r[i]=1
        else :
            r[i]= -1  
    
    r2 = np.zeros(n, dtype = int) 
    for i in range(n):
        if int(y_test_pred[i])==1 :
            r2[i]=1
        else :
            r2[i]= -1          
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        for i in range(n):
                data[j][i]= datax.iloc[j,i]
                if data[j][i]== 1 :
                    a=a+1
                    if r[i]==1:
                         acc1=acc1+1 

        print("ACTUAL----------total ,accepted, aceeptance rate:")             
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP)
    
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        prec=0
        reca=0
        accur=0
        FP=0
        FN=0
        TP=0
        TN=0
        for i in range(n):
             if data[j][i]== 1 :
                    a=a+1
                    if r2[i]==1:
                        acc1=acc1+1 
                        if r[i]==1:
                            TP=TP+1
                        else:
                             FP=FP+1                
                    else:
                        if r[i]==1:
                            FN=FN+1
                        else:
                            TN=TN+1    
        
        print("prec reca accuracy for each sens") 
        prec= float(TP/(TP+FP))
        reca= float(TP/(TP+FN))
        accur= float((TP+TN)/a)
        print(prec,reca,accur)
        
        print("RanomForest----------total , accepted, aceeptance rate:")             
        
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP) 
    
    print("SVM accuracy--------------------------")
    prec=0
    reca=0
    accur=0
    FP=0
    FN=0
    TP=0
    TN=0
    for i in range(n):
            if r2[i]==1:
                acc1=acc1+1 
                if r[i]==1:
                    TP=TP+1
                else:
                     FP=FP+1                
            else:
                if r[i]==1:
                     FN=FN+1
                else:
                     TN=TN+1    

        
    prec= float(TP/(TP+FP))
    reca= float(TP/(TP+FN))
    accur= float((TP+TN)/n)
    print(prec,reca,accur)
    
    
#     delta1=[.70,.75,.80,.85,.90,.95]
    #gamma=.05,.06,.07
    #delta1=[.80,.85,.90,.95]
# (for reproducibility)  

# delta1=[.8], gama=[.1], epsilon=[.05]  
# delta1=[.8], gama=[.15], epsilon=[.01]
 
#     delta1=np.arange(1,.79,-.01)
    delta=1
#     gama=[.05,.1,.15,.2,.25]
#     epsilon=[.01,.02,.05,.1,.15,.20,.25,.30,.35,.40,.50]

#ADULT ZAFAR =? epsilon=[0.088 ,0.1656, 0.168,  0.211, 0.251 ] 
 
#agarwal=> epsilon=[ 0.071, 0.1271, 0.2437, 0.27 ]
 

    #gama=[0.0869, 0.0521,0.0782, 0.0608,0.0434, 0.1,0.069,0.0434,0.034]
    epsilon=[.01]
    beta_converge = [0.15,0.20]
    alpha = [0,0.06,0.062,0.065,0.07,0.8]
    
    zero_one = np.zeros(n, dtype = int) 
    
    fi= np.zeros(n,dtype=int) 
#     for delta in delta1:
    #4 gamma=[0.175442,    0.142103, 0.166039,    0.164754,  0.153465,    0.14,  0.104348   ]
    #lp_equalized_odds_no_beta(data1,eps,y_test,e,beta_avg,alpha)
    #1 gamma=[0.259147,   0.0730028, 0.210139, 0.0893443, 0.306931, 0.0933333,  0.0347826]
    #gamma=[0.196178,0.126722,   0.179654, 0.140164,     0.153465,   0.133333,  0.0695652]

  
    gamma = [0.175442,    0.142103, 0.166039,    0.164754,  0.153465,    0.14,  0.104348 ]
    for eps in epsilon:
        for beta_avg in beta_converge:
            print("----------------This is for covergence at beta = ",beta_avg, " ----------------")
            for a in alpha:
                u1,u2=lp_equalized_odds(data,eps,y_test_pred,e,beta_avg,a)
                #######################Disp_impact#######################  
                print("gamma-epsilon-delta",gamma,eps,delta)
                accu_all=[]
                DP_all=[]
                precision_all=[]
                recall_all=[]
                acceptance_rate=np.zeros((7,28),dtype=float)
                count=0
                print("<--------------------------------------->")
            #        print("iteration t",t)
            #                 for alpha in np.arange(0,1.05,0.05):
            #                     print("alpha: ",alpha)
            #                     for i in range(n):

            #                         z=random()
            #                         if z < alpha:
            #                                fi[i]= u1[i] 

            #                         else:
            #                                fi[i]= r2[i]
                
                for i in range(n):
                    fi[i] = u1[i]
                    if (fi[i]==1):
                        zero_one[i] = 1
                    else:
                        zero_one[i] = 0
                ar=[]
                #find_eo_stats(y_test,zero_one)
                find_eo_stats_multiple(y_test,zero_one)


                for j in range(s):
                    print("sensitive attribute ",(j+1)) 

                    TP=0
                    FP=0
                    FN=0
                    TN=0
                    precision=0
                    recall=0
                    for i in range(n):
                         if data[j][i]== 1 :                        
                            if fi[i]==1 and r[i]==1:
                                TP=TP+1
                            if fi[i]==1 and r[i]==-1:
                                FP=FP+1 
                            if fi[i]==-1 and r[i]==1:
                                FN=FN+1
                            if fi[i]==-1 and r[i]==-1:
                                TN=TN+1    
                    if TP+FP !=0:
                        precision=float(TP/(TP+FP))
                    print("precision",precision)
                    if TP+FN !=0:    
                        recall=float(TP/(TP+FN))
                    print("recall",recall)
                    if FP+TN !=0:
                        fpr = float(FP/(FP+TN))
                    print("FPR", fpr)    
                    print("TP,FP,TN,FN")
                    print(TP,FP,TN,FN)
                    a=0
                    b=0
                    acc1=0
                    acc2=0
                    for i in range(n):
                            if data[j][i]== 1 :
                                a=a+1
                                if fi[i]==1:
                                     acc1=acc1+1 

            #                         print("total ,fair accepted, aceeptance rate:")             
                    a1=float(acc1/a)



            #                         print(a)
            #                         print(acc1)
            #                         print(a1)
                    ar.append(a1)

                count = count+1
                maxi=max(ar)
                mini= min(ar)
                DP=float(maxi-mini)
                print("acceptance rates")
                print(ar)
                print("DP")
                print(DP)
                f_acc=0
                for i in range(n):
                     if fi[i] == r[i]:
                            f_acc=f_acc+1
                f_acc_l=float((f_acc*100)/n) 

#######################################################################33   

#                         print("sensitive attribute ",(j+1)) 





        TP=0
        FP=0
        FN=0
        TN=0
        precision=0
        recall=0
        for i in range(n):
                if fi[i]==1 and r[i]==1:
                    TP=TP+1
                if fi[i]==1 and r[i]==-1:
                    FP=FP+1 
                if fi[i]==-1 and r[i]==1:
                    FN=FN+1
                if fi[i]==-1 and r[i]==-1:
                    TN=TN+1    

        if TP+FP!=0:
            precision=float(TP/(TP+FP))
        print("precision",precision)
        if TP+FN!=0:
            recall=float(TP/(TP+FN))    

        print("recall",recall)
        
        accu = float((TP + TN)/n)
        print("TP,FP,TN,FN")
        print(TP,FP,TN,FN)
#       print("total ,fair accepted, aceeptance rate:")             
        a1=float(acc1/a)


    print("<--------------------------------------->")
    alpha_weight=np.arange(0,1.05,.05)        
    return accu_all,DP_all,acceptance_rate,alpha_weight